// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgstore

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type PaymentMethod struct {
	ID   uuid.UUID `json:"id"`
	Key  string    `json:"key"`
	Name string    `json:"name"`
}

type Product struct {
	ID          uuid.UUID      `json:"id"`
	UserID      uuid.UUID      `json:"user_id"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	IsNew       bool           `json:"is_new"`
	Price       pgtype.Numeric `json:"price"`
	AcceptTrade bool           `json:"accept_trade"`
	IsActive    pgtype.Bool    `json:"is_active"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type ProductImage struct {
	ID        uuid.UUID `json:"id"`
	ProductID uuid.UUID `json:"product_id"`
	Path      string    `json:"path"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ProductPaymentMethod struct {
	ProductID       uuid.UUID `json:"product_id"`
	PaymentMethodID uuid.UUID `json:"payment_method_id"`
}

type RefreshToken struct {
	ID        uuid.UUID `json:"id"`
	ExpiresIn int32     `json:"expires_in"`
	UserID    uuid.UUID `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID        uuid.UUID   `json:"id"`
	Name      string      `json:"name"`
	Email     string      `json:"email"`
	Tel       string      `json:"tel"`
	Password  string      `json:"password"`
	Avatar    pgtype.Text `json:"avatar"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}
