// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products 
    ("user_id", "name", "description", "is_new", "price", "accept_trade")
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, name, description, is_new, price, accept_trade, is_active, created_at, updated_at
`

type CreateProductParams struct {
	UserID      uuid.UUID `json:"user_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	IsNew       bool      `json:"is_new"`
	Price       float64   `json:"price"`
	AcceptTrade bool      `json:"accept_trade"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.IsNew,
		arg.Price,
		arg.AcceptTrade,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.IsNew,
		&i.Price,
		&i.AcceptTrade,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductsByUserID = `-- name: GetProductsByUserID :many
SELECT id, user_id, name, description, is_new, price, accept_trade, is_active, created_at, updated_at
FROM products 
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetProductsByUserID(ctx context.Context, userID uuid.UUID) ([]Product, error) {
	rows, err := q.db.Query(ctx, getProductsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.IsNew,
			&i.Price,
			&i.AcceptTrade,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
