// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_images.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

const createProductImage = `-- name: CreateProductImage :one
INSERT INTO product_images 
    ("product_id", "path")
VALUES ($1, $2)
RETURNING id, product_id, path, created_at, updated_at
`

type CreateProductImageParams struct {
	ProductID uuid.UUID `json:"product_id"`
	Path      string    `json:"path"`
}

func (q *Queries) CreateProductImage(ctx context.Context, arg CreateProductImageParams) (ProductImage, error) {
	row := q.db.QueryRow(ctx, createProductImage, arg.ProductID, arg.Path)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Path,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductImagesByProductID = `-- name: GetProductImagesByProductID :many
SELECT id, product_id, path, created_at, updated_at
FROM product_images
WHERE product_id = $1
`

func (q *Queries) GetProductImagesByProductID(ctx context.Context, productID uuid.UUID) ([]ProductImage, error) {
	rows, err := q.db.Query(ctx, getProductImagesByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductImage
	for rows.Next() {
		var i ProductImage
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Path,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
