// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_images.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

const createProductImage = `-- name: CreateProductImage :one
INSERT INTO product_images 
    ("product_id", "path")
VALUES ($1, $2)
RETURNING id, product_id, path, created_at, updated_at
`

type CreateProductImageParams struct {
	ProductID uuid.UUID `json:"product_id"`
	Path      string    `json:"path"`
}

func (q *Queries) CreateProductImage(ctx context.Context, arg CreateProductImageParams) (ProductImage, error) {
	row := q.db.QueryRow(ctx, createProductImage, arg.ProductID, arg.Path)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Path,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
