// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_payment_methods.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

const createProductPaymentMethod = `-- name: CreateProductPaymentMethod :one
INSERT INTO product_payment_methods 
    ("product_id", "payment_method_id")
VALUES ($1, $2)
RETURNING product_id, payment_method_id
`

type CreateProductPaymentMethodParams struct {
	ProductID       uuid.UUID `json:"product_id"`
	PaymentMethodID uuid.UUID `json:"payment_method_id"`
}

func (q *Queries) CreateProductPaymentMethod(ctx context.Context, arg CreateProductPaymentMethodParams) (ProductPaymentMethod, error) {
	row := q.db.QueryRow(ctx, createProductPaymentMethod, arg.ProductID, arg.PaymentMethodID)
	var i ProductPaymentMethod
	err := row.Scan(&i.ProductID, &i.PaymentMethodID)
	return i, err
}
