// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens ("expires_in", "user_id")
VALUES ($1, $2)
    RETURNING id, expires_in, user_id, created_at
`

type CreateRefreshTokenParams struct {
	ExpiresIn int32     `json:"expires_in"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.ExpiresIn, arg.UserID)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.ExpiresIn,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec
DELETE FROM refresh_tokens
WHERE id = $1
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRefreshToken, id)
	return err
}

const getRefreshTokenByUserID = `-- name: GetRefreshTokenByUserID :one
SELECT id, expires_in, user_id, created_at
FROM refresh_tokens
WHERE user_id = $1
`

func (q *Queries) GetRefreshTokenByUserID(ctx context.Context, userID uuid.UUID) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByUserID, userID)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.ExpiresIn,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}
