// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package pgstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users ("name", "email", "tel", "password", "avatar")
VALUES ($1, $2, $3, $4, $5)
    RETURNING id, name, email, tel, password, avatar, created_at, updated_at
`

type CreateUserParams struct {
	Name     string      `json:"name"`
	Email    string      `json:"email"`
	Tel      string      `json:"tel"`
	Password string      `json:"password"`
	Avatar   pgtype.Text `json:"avatar"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Tel,
		arg.Password,
		arg.Avatar,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Tel,
		&i.Password,
		&i.Avatar,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, tel, password, avatar, created_at, updated_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Tel,
		&i.Password,
		&i.Avatar,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByTel = `-- name: GetUserByTel :one
SELECT id, name, email, tel, password, avatar, created_at, updated_at
FROM users
WHERE tel = $1
`

func (q *Queries) GetUserByTel(ctx context.Context, tel string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByTel, tel)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Tel,
		&i.Password,
		&i.Avatar,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
